[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Forms
[form]
  form = true

# Netlify Identity
[identity]
  url = "https://app.netlify.com/sites/[your-site-name]/identity"

# 開啟 Git Gateway 以供 Decap CMS 使用
[services]
  [services.git-gateway]
    enabled = true

# 開發環境設定
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"