title: "學生程式設計社"
tagline: "一起學習程式設計，創造美好未來"
logo: ""
email: "contact@programming-club.example.com"
phone: "02-1234-5678"
address: "台北市大安區示範路123號 電資大樓5樓"
social:
  facebook: "https://facebook.com/programming-club"
  instagram: "https://instagram.com/programming_club"
  youtube: "https://youtube.com/@programming-club"
  github: "https://github.com/programming-club"